### ISSUE TITLE
Allow copy and paste sync

### ISSUE THREAD

**Issue by mglaman** [panopoly/panopoly-sprint-kit#2]

**Comment by dsnopek** [comment]
This is just a VirtualBox setting because we already have the guest extensions installed. So, it's some change to the JSON file for Packer.

**Comment by dsnopek** [comment]
I think I figured out how to do this. Just need to test it!

**Comment by dsnopek** [comment]
Fixed in 183c04dda0a6b6ba0e2b330905d607191bae84e2
